// <auto-generated />
using System;
using EasyLingo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyLingo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("EasyLingo.Data.Entities.Language", b =>
                {
                    b.Property<int>("LangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LangId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LangId = 1,
                            Code = "EN",
                            Name = "Angielski"
                        },
                        new
                        {
                            LangId = 2,
                            Code = "DE",
                            Name = "Niemiecki"
                        });
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LangId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SetCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetId");

                    b.HasIndex("LangId");

                    b.HasIndex("SetCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TermId");

                    b.HasIndex("SetId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "xRIOwBtqQtojAWUmIzZ7RA==:uU4pOJVA15NFGTSOhjuOJ5o7YGdR2U+d9RAd7skxGh4=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserSetCategory", b =>
                {
                    b.Property<int>("SetCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSetCategories");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserSetProgress", b =>
                {
                    b.Property<int>("UserProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserProgressId");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSetProgresses");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserTermStatus", b =>
                {
                    b.Property<int>("UserTermStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserTermStatusId");

                    b.HasIndex("TermId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTermStatuses");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Set", b =>
                {
                    b.HasOne("EasyLingo.Data.Entities.Language", "Language")
                        .WithMany("Sets")
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyLingo.Data.Entities.UserSetCategory", "SetCategory")
                        .WithMany("Sets")
                        .HasForeignKey("SetCategoryId");

                    b.HasOne("EasyLingo.Data.Entities.User", "User")
                        .WithMany("Sets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("SetCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Term", b =>
                {
                    b.HasOne("EasyLingo.Data.Entities.Set", "Set")
                        .WithMany("Terms")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserSetCategory", b =>
                {
                    b.HasOne("EasyLingo.Data.Entities.User", "User")
                        .WithMany("UserSetCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserSetProgress", b =>
                {
                    b.HasOne("EasyLingo.Data.Entities.Set", "Set")
                        .WithMany("UserSetProgresses")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyLingo.Data.Entities.User", "User")
                        .WithMany("UserSetProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserTermStatus", b =>
                {
                    b.HasOne("EasyLingo.Data.Entities.Term", "Term")
                        .WithMany("UserTermStatuses")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyLingo.Data.Entities.User", "User")
                        .WithMany("UserTermStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Language", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Set", b =>
                {
                    b.Navigation("Terms");

                    b.Navigation("UserSetProgresses");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.Term", b =>
                {
                    b.Navigation("UserTermStatuses");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.User", b =>
                {
                    b.Navigation("Sets");

                    b.Navigation("UserSetCategories");

                    b.Navigation("UserSetProgresses");

                    b.Navigation("UserTermStatuses");
                });

            modelBuilder.Entity("EasyLingo.Data.Entities.UserSetCategory", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
